# Generated by Django 4.1.7 on 2023-02-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=10)),
            ],
        ),
    ]
